apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginbbs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loginbbs
  template:
    metadata:
      labels:
        app: loginbbs
    spec:
      containers:
      - name: loginbbs
        image: gauravkumar4578/loginbbs:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "13.49.80.132"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "login_db"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
